/**
 * Resource directory data for Brevard, Volusia, and Orange Counties.
 *
 * CORRECTNESS RULES
 * - Every entry must be traceable to the organization's own website or an official
 *   government list. Do not add an entry from memory or from a third-party directory
 *   alone; those are consistently wrong about hours and phone numbers.
 * - Never invent a phone number. Where no public number exists, leave `phone` empty
 *   and the UI hides the call button rather than dialing a wrong number.
 * - Coordinates are the real geocoded location of the address, not the town centre.
 *   Reusing a town centre makes the "miles away" sort misleading, which is worse than
 *   showing no distance at all.
 * - `schedule` is only for hours published by the organization. When sources
 *   disagree, leave it empty and say so in `hoursText` — a wrong "Open now" badge
 *   sends someone on a wasted trip.
 * - `lastVerified` records the last check against the source.
 */

export type ResourceCategory =
  | "Food Banks"
  | "Churches & Faith-Based"
  | "Charity Free Services"
  | "Shelters & Housing"
  | "Showers & Hygiene";

export type ResourceCounty = "Brevard" | "Volusia" | "Orange" | "Statewide";

export type TriageNeed = "shelter" | "food" | "travel" | "id_tech";

export type Resource = {
  id: string;
  name: string;
  category: ResourceCategory;
  address: string;
  lat: number;
  lng: number;
  phone: string;
  website?: string;
  description: string;
  hoursText: string;
  /**
   * Opening ranges keyed by weekday (Sunday 0 … Saturday 6). A day maps to a LIST of
   * ranges because plenty of organizations close over lunch or run a morning and an
   * evening session; collapsing those into one span would show "open" during hours
   * the doors are actually shut.
   */
  schedule: Partial<Record<number, Array<[number, number]>>>;
  tags: string[];
  partnerType: string;
  capacityStatus: string;
  triageCategory: TriageNeed;
  county: ResourceCounty;
  /** ISO date the listing was last checked against the organization's own website. */
  lastVerified?: string;
  /**
   * True when the organization has no public walk-in location, or is a phone-based
   * service. Distance and street directions are meaningless for these entries, so the
   * UI must not present them as a place to travel to.
   */
  mobileOnly?: boolean;
};

export type TownName =
  "Cocoa" |
  "Cocoa Beach" |
  "Daytona Beach" |
  "DeLand" |
  "Edgewater" |
  "Melbourne" |
  "Merritt Island" |
  "Mims" |
  "Mobile" |
  "National" |
  "New Smyrna Beach" |
  "Orlando" |
  "Ormond Beach" |
  "Rockledge" |
  "Scottsmoor" |
  "Statewide" |
  "Titusville" |
  "Viera" |
  "Winter Garden";

export type Coordinates = { lat: number; lng: number };

export const PRESET_TOWNS: Record<TownName, Coordinates> = {
  "Cocoa": { lat: 28.3582, lng: -80.7302 },
  "Cocoa Beach": { lat: 28.32, lng: -80.6075 },
  "Daytona Beach": { lat: 29.2108, lng: -81.0228 },
  "DeLand": { lat: 29.0343, lng: -81.3035 },
  "Edgewater": { lat: 28.9886, lng: -80.902 },
  "Melbourne": { lat: 28.0784, lng: -80.6026 },
  "Merritt Island": { lat: 28.5392, lng: -80.672 },
  "Mims": { lat: 28.6653, lng: -80.8481 },
  "Mobile": { lat: 28.7617, lng: -80.8625 },
  "National": { lat: 28.7617, lng: -80.8625 },
  "New Smyrna Beach": { lat: 29.0258, lng: -80.927 },
  "Orlando": { lat: 28.5383, lng: -81.3792 },
  "Ormond Beach": { lat: 29.2858, lng: -81.0559 },
  "Rockledge": { lat: 28.3161, lng: -80.7262 },
  "Scottsmoor": { lat: 28.7617, lng: -80.8625 },
  "Statewide": { lat: 28.7617, lng: -80.8625 },
  "Titusville": { lat: 28.6133, lng: -80.8091 },
  "Viera": { lat: 28.2453, lng: -80.7401 },
  "Winter Garden": { lat: 28.5653, lng: -81.5862 },
};

export const TOWN_NAMES = Object.keys(PRESET_TOWNS) as TownName[];

/**
 * Keys in PRESET_TOWNS that are filter buckets rather than places.
 *
 * All three share Scottsmoor's coordinates, so naming one would tell a visitor standing
 * in Scottsmoor that they are in "Statewide". They exist so the directory can be scoped
 * by reach, and must never be presented as a location.
 */
const NON_GEOGRAPHIC_TOWNS = new Set<TownName>(["Mobile", "National", "Statewide"]);

/**
 * The real town nearest a coordinate, or null when nothing is close enough.
 *
 * Returning null past `maxMiles` matters: a visitor in the panhandle is 250 miles from
 * the nearest town in this list, and naming "Titusville" there would be a confident
 * wrong answer about where they are standing.
 */
export function nearestTownName(coords: Coordinates, maxMiles = 30): string | null {
  let best: TownName | null = null;
  let bestDist = Infinity;
  for (const name of TOWN_NAMES) {
    if (NON_GEOGRAPHIC_TOWNS.has(name)) continue;
    const d = calculateDistanceMiles(coords.lat, coords.lng, PRESET_TOWNS[name].lat, PRESET_TOWNS[name].lng);
    if (d < bestDist) {
      bestDist = d;
      best = name;
    }
  }
  return best !== null && bestDist <= maxMiles ? best : null;
}

export const CATEGORIES: Array<"All" | ResourceCategory> = [
  "All",
  "Food Banks",
  "Shelters & Housing",
  "Showers & Hygiene",
  "Churches & Faith-Based",
  "Charity Free Services",
];

export const FILTER_TAGS = [
  "All",
  "No ID Required",
  "Open Residency",
  "Showers",
  "Tech Assistance",
  "Groceries",
  "Hot Meals",
  "Cold Night Shelter",
  "Rent Help",
  "Veterans",
  "North Brevard",
  "Volusia",
  "Orange County",
  "Statewide",
] as const;

export const BREVARD_RESOURCES: Resource[] = [
  {
    id: "res-1",
    name: "United North Brevard Food Pantry",
    category: "Food Banks",
    address: "412 Main St, Titusville, FL 32796",
    lat: 28.6126959,
    lng: -80.8096831,
    phone: "(321) 269-6555",
    website: "https://northbrevardcharities.org/what-we-do/food-pantry.html",
    description: "Choice food pantry run jointly by North Brevard Charities and First United Methodist Church. Non-perishable food, canned goods, refrigerated items, and fresh produce. Free, no special requirements.",
    hoursText: "Tuesday & Friday 11:00 AM – 3:00 PM",
    schedule: {2: [[11, 15]], 5: [[11, 15]]},
    tags: ["Groceries", "Fresh Produce", "North Brevard", "No ID Required", "TEFAP"],
    partnerType: "Second Harvest Healthy Pantry",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-2",
    name: "North Brevard Charities",
    category: "Charity Free Services",
    address: "4495 S Hopkins Ave, Titusville, FL 32780",
    lat: 28.6133,
    lng: -80.8091,
    phone: "(321) 269-6555",
    website: "https://northbrevardcharities.org/",
    description: "Housing assistance and placement, emergency financial help, and donation pickups. Serving North Brevard for over 50 years. Affiliated thrift store at 4475 S Hopkins Ave.",
    hoursText: "Office Mon–Thu; Thrift Store Mon–Wed 9:00 AM – 5:00 PM, Thu 10:00 AM – 4:00 PM",
    schedule: {},
    tags: ["Rent Help", "Housing Help", "Thrift Store", "North Brevard"],
    partnerType: "Verified Non-Profit",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-3",
    name: "No One Hungry — Pine St Pantry",
    category: "Food Banks",
    address: "418 Pine St, Titusville, FL 32780",
    lat: 28.6103915,
    lng: -80.8093578,
    phone: "(321) 567-4408",
    website: "https://www.noonehungryfl.org/",
    description: "Food pantry plus home delivery of food to seniors and outreach with food and personal items to people experiencing homelessness. ID or proof of Brevard County residency required.",
    hoursText: "Tuesdays 10:00 AM – 12:00 PM",
    schedule: {2: [[10, 12]]},
    tags: ["Groceries", "Senior Delivery", "North Brevard", "ID Required"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-4",
    name: "St. Gabriel's Episcopal Church",
    category: "Churches & Faith-Based",
    address: "414 Pine St, Titusville, FL 32796",
    lat: 28.6102237,
    lng: -80.8100403,
    phone: "(321) 267-2545",
    website: "https://stgabriels.church/",
    description: "Faith community and home of the No One Hungry food ministry, which runs the Pine St Pantry behind the church.",
    hoursText: "Office Mon–Fri 9:00 AM – 12:00 PM; services Sun 7:30 AM & 10:15 AM",
    schedule: {},
    tags: ["Faith-Based", "North Brevard", "Community"],
    partnerType: "Faith Partner",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-5",
    name: "Sharing Center of Central Brevard",
    category: "Food Banks",
    address: "113 Aurora St, Cocoa, FL 32922",
    lat: 28.354285,
    lng: -80.748867,
    phone: "(321) 631-0306",
    website: "https://sharingcenter.org/food-pantry/",
    description: "Food pantry, community kitchen with hot meals, showers, clothing, and household and hygiene items, plus limited financial assistance and referrals. A day center — there are no overnight beds. Also activates as a cold-night shelter when the overnight low reaches 45°F. Clients may use the pantry once every 60 days.",
    hoursText: "Pantry Mon–Fri 9:00 AM – 12:00 PM & 1:00 – 3:00 PM; TEFAP first Monday",
    schedule: {1: [[9, 12], [13, 15]], 2: [[9, 12], [13, 15]], 3: [[9, 12], [13, 15]], 4: [[9, 12], [13, 15]], 5: [[9, 12], [13, 15]]},
    tags: ["Groceries", "Hot Meals", "Showers", "Clothing", "Open Residency", "Cold Night Shelter"],
    partnerType: "Regional Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-6",
    name: "Providence Connects",
    category: "Food Banks",
    address: "17 E Hibiscus Blvd, Melbourne, FL 32901",
    lat: 28.0851218,
    lng: -80.6211958,
    phone: "(321) 723-1060",
    website: "https://www.providenceconnects.org/programs",
    description: "Formerly South Brevard Sharing Center, now merged with Daily Bread. Choose-your-own food pantry, mobile food truck with hot meals, hot showers and mobile case management via street-outreach units, housing-focused outreach, and SNAP and health-insurance enrollment help. Rental and utility assistance are currently unfunded.",
    hoursText: "Pantry Tue & Thu 9:00–11:30 AM & 1:00–4:00 PM; Wed 1:00–4:00 PM plus drive-through 4:00–6:00 PM; Fri 9:00 AM – 4:00 PM; Sat drive-through 9:00 AM – 12:00 PM",
    schedule: {2: [[9, 11.5], [13, 16]], 3: [[13, 16]], 4: [[9, 11.5], [13, 16]], 5: [[9, 16]]},
    tags: ["Groceries", "Showers", "Hot Meals", "SNAP Help", "South Brevard", "Mobile Services"],
    partnerType: "Regional Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-7",
    name: "LifePointe Ministries",
    category: "Shelters & Housing",
    address: "4220 S Hopkins Ave, Titusville, FL 32780",
    lat: 28.5641946,
    lng: -80.8023439,
    phone: "(321) 383-0254",
    website: "https://www.lifepointeministries.org/",
    description: "Thursday Table serves a free hot meal with hot showers and hygiene care items (showers via Streetside Showers). Clothing and hygiene warehouse, and the only inclement-weather / cold-night shelter between Titusville and Port Orange. Sunday worship and a Monday-evening bingo fundraiser.",
    hoursText: "Thursday Table 4:30 – 6:30 PM; Sunday service 10:30 AM; call for cold-night activation",
    schedule: {0: [[10.5, 11.5]], 4: [[16.5, 18.5]]},
    tags: ["Hot Meals", "Showers", "Hygiene", "Cold Night Shelter", "North Brevard", "Faith-Based"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-8",
    name: "Under The Bridge Ministries",
    category: "Churches & Faith-Based",
    address: "Sand Point Park (A. Max Brewer Bridge), Titusville, FL 32780",
    lat: 28.6133,
    lng: -80.8091,
    phone: "",
    description: "Weekly Monday-night outreach under the A. Max Brewer Bridge in partnership with Hope for North Brevard: home-cooked hot meal, blankets and supplies for people experiencing homelessness. Meets outdoors; no published phone number.",
    hoursText: "Mondays 6:00 PM",
    schedule: {1: [[18, 20]]},
    tags: ["Hot Meals", "Outreach", "Supplies", "North Brevard", "Faith-Based"],
    partnerType: "Faith Partner",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-9",
    name: "Corjesus Food Pantry (St. Teresa Catholic Church)",
    category: "Food Banks",
    address: "2306 S Hopkins Ave, Titusville, FL 32780",
    lat: 28.5887545,
    lng: -80.8066531,
    phone: "(321) 607-6816",
    description: "Food pantry. ID required; eligible to receive food every other month.",
    hoursText: "Mondays, Wednesdays & Fridays 9:30 – 11:30 AM",
    schedule: {1: [[9.5, 11.5]], 3: [[9.5, 11.5]], 5: [[9.5, 11.5]]},
    tags: ["Groceries", "ID Required", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-10",
    name: "First United Methodist Church of Titusville",
    category: "Food Banks",
    address: "206 S Hopkins Ave, Titusville, FL 32796",
    lat: 28.6133848,
    lng: -80.8082011,
    phone: "(321) 269-7631",
    description: "Food pantry plus a free weekly Saturday breakfast. No requirements. Co-sponsor of the United North Brevard Food Pantry.",
    hoursText: "Pantry Friday 1:00 – 3:00 PM; breakfast Saturday 8:00 – 9:00 AM",
    schedule: {5: [[13, 15]], 6: [[8, 9]]},
    tags: ["Groceries", "Breakfast", "No ID Required", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-11",
    name: "Mims United Methodist Church Food Pantry",
    category: "Food Banks",
    address: "3302 Green St, Mims, FL 32754",
    lat: 28.6660679,
    lng: -80.8464962,
    phone: "(321) 267-6202",
    description: "Food pantry. No requirements; once per month, up to four times per year. The closest pantry to Scottsmoor.",
    hoursText: "Tuesdays 10:00 AM – 12:00 PM (or until food runs out)",
    schedule: {2: [[10, 12]]},
    tags: ["Groceries", "No ID Required", "North Brevard", "Mims"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-12",
    name: "Holy Spirit Catholic Church Food Pantry",
    category: "Food Banks",
    address: "2399 Holder Rd, Mims, FL 32754",
    lat: 28.6611966,
    lng: -80.8648152,
    phone: "(321) 269-2282",
    description: "Food pantry. Proof of residence with ID required; zip codes must be 32754 or 32796. Serves Mims and the Scottsmoor area.",
    hoursText: "2nd, 3rd, 4th & 5th Wednesdays 11:00 AM – 1:00 PM",
    schedule: {3: [[11, 13]]},
    tags: ["Groceries", "ID Required", "North Brevard", "Mims"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-13",
    name: "New Life Space Coast Food Pantry",
    category: "Food Banks",
    address: "6755 S Washington Ave, Titusville, FL 32780",
    lat: 28.5985,
    lng: -80.8148,
    phone: "(321) 269-7578",
    description: "Food pantry. Bring an ID and, if possible, a Social Security card.",
    hoursText: "Thursdays 11:00 AM – 1:00 PM",
    schedule: {4: [[11, 13]]},
    tags: ["Groceries", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-14",
    name: "Gateway Community Church Food Pantry",
    category: "Food Banks",
    address: "2801 Tropic St, Titusville, FL 32796",
    lat: 28.611703,
    lng: -80.8363635,
    phone: "(321) 267-7064",
    description: "Food pantry. No requirements.",
    hoursText: "2nd & 4th Tuesdays 10:00 AM – 1:00 PM",
    schedule: {2: [[10, 13]]},
    tags: ["Groceries", "No ID Required", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-15",
    name: "Good Shepherd Lutheran Church Food Pantry",
    category: "Food Banks",
    address: "2073 Garden St, Titusville, FL 32796",
    lat: 28.6152303,
    lng: -80.8280718,
    phone: "(321) 267-4323",
    description: "Food pantry. No requirements.",
    hoursText: "2nd & last Tuesdays 9:30 AM – 12:00 PM",
    schedule: {2: [[9.5, 12]]},
    tags: ["Groceries", "No ID Required", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-16",
    name: "Brevard Adventist Community Services Food Pantry",
    category: "Food Banks",
    address: "5005 Barna Ave, Titusville, FL 32780",
    lat: 28.5515713,
    lng: -80.8225139,
    phone: "(321) 267-8893",
    description: "Food pantry run with Titusville Seventh-day Adventist Church.",
    hoursText: "2nd Thursday 1:00 – 3:00 PM and 4:00 – 6:00 PM",
    schedule: {4: [[13, 15], [16, 18]]},
    tags: ["Groceries", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-17",
    name: "Hope for North Brevard",
    category: "Charity Free Services",
    address: "2214 Garden St, Titusville, FL 32796",
    lat: 28.6154046,
    lng: -80.8300964,
    phone: "(321) 383-8638",
    website: "https://www.hopenb.org/",
    description: "Community nonprofit coordinating homelessness care, food, and family support across North Brevard. Partners with Under The Bridge Ministries on the Monday-night outreach.",
    hoursText: "Call for hours",
    schedule: {},
    tags: ["Referrals", "Homelessness Care", "North Brevard"],
    partnerType: "Community Partner",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-18",
    name: "North Brevard Church of Christ Food Pantry",
    category: "Food Banks",
    address: "3585 S Park Ave, Titusville, FL 32780",
    lat: 28.5737219,
    lng: -80.8444394,
    phone: "(321) 269-1001",
    description: "Food pantry. No requirements. Hours are published differently by two City of Titusville documents — call before going.",
    hoursText: "Call to confirm (published as 1st & 3rd Mondays 1:00 – 3:00 PM)",
    schedule: {1: [[13, 15]]},
    tags: ["Groceries", "Call to Confirm", "North Brevard"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-19",
    name: "Titusville Hope Center & Thrift",
    category: "Charity Free Services",
    address: "664 S Park Ave, Titusville, FL 32796",
    lat: 28.6083247,
    lng: -80.8187091,
    phone: "(321) 362-5418",
    description: "Thrift store and community assistance ministry. Not affiliated with St. Gabriel's Episcopal Church.",
    hoursText: "Call for hours",
    schedule: {},
    tags: ["Thrift Store", "North Brevard"],
    partnerType: "Community Partner",
    capacityStatus: "Call for availability",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-20",
    name: "Hummingbird Pantry",
    category: "Food Banks",
    address: "3000 Jolly St, Building 4, Titusville, FL 32780",
    lat: 28.6133,
    lng: -80.8091,
    phone: "",
    description: "Food pantry with curbside pickup, no ID required. The schedule is posted only on the pantry's Facebook page, and two published phone numbers disagree — treat the number as unconfirmed.",
    hoursText: "Varies — check the pantry's Facebook page",
    schedule: {},
    tags: ["Groceries", "Curbside", "No ID Required", "Call to Confirm", "North Brevard"],
    partnerType: "Grassroots Partner",
    capacityStatus: "Call for availability",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-21",
    name: "Salvation Army of Brevard — North/Central",
    category: "Charity Free Services",
    address: "919 Peachtree St, Cocoa, FL 32922",
    lat: 28.3575446,
    lng: -80.7416991,
    phone: "(321) 632-6060",
    website: "https://southernusa.salvationarmy.org/",
    description: "Emergency assistance, food, and social services for North and Central Brevard.",
    hoursText: "Call for hours",
    schedule: {},
    tags: ["Groceries", "Emergency Assistance", "Rent Help"],
    partnerType: "Regional Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-22",
    name: "Streetside Showers",
    category: "Showers & Hygiene",
    address: "Mobile — Brevard County, Mobile, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "",
    website: "https://streetsideshowers.com/",
    description: "Mobile shower trailer bringing hot showers, hygiene kits, and a clean change of clothes to people experiencing homelessness across Brevard County. No fixed location — check the published schedule.",
    hoursText: "Rotating schedule — check the website",
    schedule: {},
    tags: ["Showers", "Hygiene", "Mobile Services", "No ID Required"],
    partnerType: "Mobile Service",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-23",
    name: "Daily Bread Inc.",
    category: "Charity Free Services",
    address: "815 E Fee Ave, Melbourne, FL 32901",
    lat: 28.0784,
    lng: -80.6026,
    phone: "(321) 723-1060",
    website: "https://www.dailybreadinc.org",
    description: "The soup kitchen and day shelter closed on May 9, 2025. Daily Bread now operates a mobile food truck and housing and outreach programs, merged into Providence Connects. There is no walk-in lunch service any more.",
    hoursText: "No public walk-in hours — mobile outreach only",
    schedule: {},
    tags: ["Mobile Services", "Housing Help", "South Brevard", "No Walk-In"],
    partnerType: "Regional Partner",
    capacityStatus: "Call for availability",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-24",
    name: "Matthew's Hope Ministries",
    category: "Charity Free Services",
    address: "825 Forrest Ave, Cocoa, FL 32922",
    lat: 28.3654652,
    lng: -80.7328834,
    phone: "",
    website: "https://www.matthewshopeministries.org/",
    description: "Day-outreach ministry serving guests on outreach days, with a food pantry and 14 earned transitional housing units. NOT an emergency shelter and NOT a soup kitchen. Its Cocoa campus also hosts cold-weather shelter activation during freeze events.",
    hoursText: "Outreach days (commonly Tue & Thu) — call for hours",
    schedule: {},
    tags: ["Outreach", "Groceries", "Transitional Housing", "Cold Night Shelter", "No Walk-In"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-25",
    name: "CITA Rescue Mission — Men's Campus",
    category: "Shelters & Housing",
    address: "2330 Johnny Ellison Dr, Melbourne, FL 32901",
    lat: 28.0734546,
    lng: -80.6019282,
    phone: "(321) 366-0031",
    website: "https://citarescuemission.org/",
    description: "52-bed men's recovery campus and emergency shelter with an addiction-recovery program. Emergency and intake available 24/7 at this campus.",
    hoursText: "Emergency & intake 24/7; office Mon–Fri 8:00 AM – 4:00 PM",
    schedule: {},
    tags: ["Shelter", "Men", "Recovery", "Meals", "South Brevard"],
    partnerType: "Faith-Based",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-26",
    name: "CITA Rescue Mission — Women & Children's Center",
    category: "Shelters & Housing",
    address: "Melbourne, Melbourne, FL",
    lat: 28.0784,
    lng: -80.6026,
    phone: "(321) 294-5493",
    website: "https://citarescuemission.org/contact-hours/",
    description: "Temporary shelter for women with children and pregnant women aged 18 and over, plus a women's recovery program. The street address is not published — call for directions.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM; emergencies answered 24/7 (not intake)",
    schedule: {},
    tags: ["Shelter", "Women", "Children", "Recovery", "Call Ahead"],
    partnerType: "Faith-Based",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-27",
    name: "Family Promise Space Coast",
    category: "Shelters & Housing",
    address: "114 1st St, Cocoa, FL 32922",
    lat: 28.3579701,
    lng: -80.7314396,
    phone: "",
    website: "https://www.fpspacecoast.org/needhelp",
    description: "Emergency shelter and eviction prevention for families with at least one minor child aged 17 or under. Referral-based, not walk-in — submit the online Family Shelter Application or Eviction Prevention form and staff respond within 24–48 business hours. Average stay about 30 days.",
    hoursText: "Building open Mon–Fri 9:00 AM – 5:00 PM (by application)",
    schedule: {},
    tags: ["Shelter", "Families", "Eviction Prevention", "Case Management", "Application Required"],
    partnerType: "Regional Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-28",
    name: "His Place Ministries (Cold Night Shelter)",
    category: "Shelters & Housing",
    address: "1842 S Harbor City Blvd, Melbourne, FL 32901",
    lat: 28.0804142,
    lng: -80.603606,
    phone: "(321) 674-9009",
    description: "South Brevard cold-night shelter, activating on nights when the temperature drops below 45°F. Hot evening meal, overnight sleeping space, and breakfast. Volunteer-run with limited space — always confirm activation by phone or through 2-1-1 first.",
    hoursText: "On activation nights: opens 8:00 PM, closes 7:00 AM",
    schedule: {},
    tags: ["Cold Night Shelter", "Hot Meals", "South Brevard", "Call First"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-29",
    name: "Our Savior Cold Night Ministries",
    category: "Shelters & Housing",
    address: "5301 N Atlantic Ave, Cocoa Beach, FL 32931",
    lat: 28.3660197,
    lng: -80.6076064,
    phone: "(321) 544-1684",
    description: "Cold-night shelter opening when temperatures drop below 40°F, or when they are in the low 40s with wind chill or rain. Meals and overnight sleeping space in the parish center next to the gym. Confirm activation before traveling.",
    hoursText: "On activation nights: opens 5:30 PM, closes 7:00 AM",
    schedule: {},
    tags: ["Cold Night Shelter", "Hot Meals", "Beachside", "Call First"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-30",
    name: "House of Hope (Cold Night Shelter)",
    category: "Shelters & Housing",
    address: "330 Magnolia Ave, Merritt Island, FL 32952",
    lat: 28.3559009,
    lng: -80.7038312,
    phone: "(321) 453-0318",
    description: "Cold-night shelter with meals and overnight sleeping space on activation nights. Confirm the night's status by phone or through 2-1-1 Brevard before sending anyone.",
    hoursText: "On activation nights: opens 5:00 PM, closes 6:30 AM",
    schedule: {},
    tags: ["Cold Night Shelter", "Hot Meals", "Merritt Island", "Call First"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-31",
    name: "Brevard Homeless Coalition",
    category: "Charity Free Services",
    address: "Rockledge, Rockledge, FL",
    lat: 28.3161,
    lng: -80.7262,
    phone: "",
    website: "https://brevardhomelesscoalition.org/",
    description: "Continuum of Care lead agency for Brevard County and the county's coordinated-entry system. It coordinates cold-weather shelter activations and posts open locations. Uses a P.O. Box; the reliable way to reach help is 2-1-1.",
    hoursText: "Call 2-1-1 for coordinated entry",
    schedule: {},
    tags: ["Coordinated Entry", "Cold Night Info", "Referrals", "Brevard"],
    partnerType: "Continuum of Care",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-32",
    name: "Brevard County Community Action Agency",
    category: "Charity Free Services",
    address: "415 Stone St, Cocoa, FL 32922",
    lat: 28.3548163,
    lng: -80.735385,
    phone: "(321) 633-1951",
    website: "https://www.brevardfl.gov/HousingAndHumanServices/CommunityActionAgency",
    description: "Emergency services including mortgage and rental assistance, utility assistance, food vouchers, prescriptions, medical and dental, burial and cremation assistance, and LIHEAP energy assistance.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM",
    schedule: {1: [[8, 17]], 2: [[8, 17]], 3: [[8, 17]], 4: [[8, 17]], 5: [[8, 17]]},
    tags: ["Rent Help", "Utilities", "LIHEAP", "Prescriptions", "Brevard"],
    partnerType: "County Program",
    capacityStatus: "High Demand",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-33",
    name: "Brevard County Housing and Human Services",
    category: "Charity Free Services",
    address: "2725 Judge Fran Jamieson Way, Viera, FL 32940",
    lat: 28.2463874,
    lng: -80.7365434,
    phone: "(321) 633-2007",
    website: "https://www.brevardfl.gov/HousingAndHumanServices",
    description: "County department running affordable housing programs, emergency rental assistance, LIHEAP energy assistance, housing rehabilitation, weatherization, fair housing, and burial assistance.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM",
    schedule: {1: [[8, 17]], 2: [[8, 17]], 3: [[8, 17]], 4: [[8, 17]], 5: [[8, 17]]},
    tags: ["Rent Help", "Utilities", "Weatherization", "Fair Housing", "Brevard"],
    partnerType: "County Program",
    capacityStatus: "High Demand",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-34",
    name: "Housing Authority of Brevard County",
    category: "Shelters & Housing",
    address: "1401 Guava Ave, Melbourne, FL 32935",
    lat: 28.0784,
    lng: -80.6026,
    phone: "(321) 775-1592",
    website: "https://www.habc.us/",
    description: "Section 8 Housing Choice Vouchers and public housing. Waitlists are currently closed and status changes — call to confirm before applying. Not an emergency service.",
    hoursText: "Mon–Thu 8:00 AM – 5:30 PM",
    schedule: {1: [[8, 17.5]], 2: [[8, 17.5]], 3: [[8, 17.5]], 4: [[8, 17.5]]},
    tags: ["Section 8", "Public Housing", "Waitlist Closed", "Brevard"],
    partnerType: "Public Agency",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-35",
    name: "Brevard Health Alliance",
    category: "Charity Free Services",
    address: "Melbourne, Melbourne, FL",
    lat: 28.0784,
    lng: -80.6026,
    phone: "(321) 733-2021",
    website: "https://www.brevardhealth.org/",
    description: "Brevard County's only Federally Qualified Health Center. Primary care and behavioral health regardless of ability to pay, with multiple clinic locations across the county and clinical social workers at partner sites.",
    hoursText: "Call for clinic hours",
    schedule: {},
    tags: ["Healthcare", "Behavioral Health", "Sliding Scale", "Brevard"],
    partnerType: "Federally Qualified Health Center",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-36",
    name: "Brevard County Legal Aid",
    category: "Charity Free Services",
    address: "1038 Harvin Way, Rockledge, FL 32955",
    lat: 28.3248137,
    lng: -80.7264438,
    phone: "(321) 631-2500",
    website: "https://brevardcountylegalaid.org/",
    description: "No-cost civil legal aid serving Brevard since 1970: eviction and housing defense, family law and domestic-violence injunctions, children's legal services, consumer law, and veterans' legal services via Mission United. Civil matters only.",
    hoursText: "Mon–Fri 8:30 AM – 12:00 PM & 1:00 – 4:00 PM",
    schedule: {1: [[8.5, 12], [13, 16]], 2: [[8.5, 12], [13, 16]], 3: [[8.5, 12], [13, 16]], 4: [[8.5, 12], [13, 16]], 5: [[8.5, 12], [13, 16]]},
    tags: ["Legal Aid", "Eviction", "Family Law", "Veterans", "Brevard"],
    partnerType: "Legal Aid",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-37",
    name: "Brevard County Veteran Services",
    category: "Charity Free Services",
    address: "2725 Judge Fran Jamieson Way, Viera, FL 32940",
    lat: 28.2463874,
    lng: -80.7365434,
    phone: "(321) 633-2012",
    website: "https://www.brevardfl.gov/HousingAndHumanServices/VeteranServices",
    description: "County Veteran Service Officers help file VA and state veterans' benefits claims and gather supporting documentation. Offices in Viera, Merritt Island, and Palm Bay.",
    hoursText: "Mon–Fri 8:00 AM – 4:30 PM",
    schedule: {1: [[8, 16.5]], 2: [[8, 16.5]], 3: [[8, 16.5]], 4: [[8, 16.5]], 5: [[8, 16.5]]},
    tags: ["Veterans", "VA Benefits", "Brevard"],
    partnerType: "County Program",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-38",
    name: "National Veterans Homeless Support",
    category: "Shelters & Housing",
    address: "1436 King St, Cocoa, FL 32922",
    lat: 28.3558591,
    lng: -80.7526493,
    phone: "(321) 208-7562",
    website: "https://nvhs.org/",
    description: "Brevard-based nonprofit working to end veteran homelessness in Central Florida through street outreach and individualized support. Toll-free 888-787-6847.",
    hoursText: "Call for hours",
    schedule: {},
    tags: ["Veterans", "Outreach", "Housing Help", "Brevard"],
    partnerType: "Veteran Service Organization",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-39",
    name: "WIC — Florida Department of Health in Brevard County",
    category: "Charity Free Services",
    address: "Cocoa, Cocoa, FL",
    lat: 28.3582,
    lng: -80.7302,
    phone: "(321) 639-5793",
    website: "https://brevard.floridahealth.gov/programs-and-services/clinical-and-nutrition-services/wic/",
    description: "WIC nutrition benefits, breastfeeding support, and nutrition education for pregnant and breastfeeding women, infants, and children under 5 who meet income guidelines. Call to schedule a certification appointment.",
    hoursText: "Call for appointment times",
    schedule: {},
    tags: ["WIC", "Nutrition", "Families", "Brevard"],
    partnerType: "Public Health",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Brevard",
    lastVerified: "2026-09-25",
  },
];

const VOLUSIA_RESOURCES: Resource[] = [
  {
    id: "res-40",
    name: "2-1-1 Volusia-Flagler / First Call For Help",
    category: "Charity Free Services",
    address: "Daytona Beach, Daytona Beach, FL",
    lat: 29.2108,
    lng: -81.0228,
    phone: "211",
    website: "https://211live.org/",
    description: "24/7 information and referral for food, shelter, utilities, health, mental health, and legal help across Volusia and Flagler counties. Free and confidential, staffed by certified specialists. Also (386) 253-0564.",
    hoursText: "24/7",
    schedule: {0: [[0, 24]], 1: [[0, 24]], 2: [[0, 24]], 3: [[0, 24]], 4: [[0, 24]], 5: [[0, 24]], 6: [[0, 24]]},
    tags: ["24/7", "Helpline", "Volusia", "Flagler", "Crisis"],
    partnerType: "Helpline",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-41",
    name: "Neighborhood Center of West Volusia",
    category: "Food Banks",
    address: "434 S Woodland Blvd, DeLand, FL 32720",
    lat: 29.0215241,
    lng: -81.3035023,
    phone: "(386) 734-8120",
    website: "https://neighborhoodcenterwv.org/",
    description: "Food pantry plus rent and utility assistance, emergency shelter, transitional and permanent supportive housing, and rapid rehousing for West Volusia families. Free grocery giveaway on the 2nd and 4th Tuesday.",
    hoursText: "Pantry Mon–Thu 9:00 AM – 12:00 PM & 1:00 – 4:00 PM, Fri 9:00 AM – 12:00 PM",
    schedule: {1: [[9, 12], [13, 16]], 2: [[9, 12], [13, 16]], 3: [[9, 12], [13, 16]], 4: [[9, 12], [13, 16]], 5: [[9, 12]]},
    tags: ["Groceries", "Rent Help", "Utilities", "Shelter", "Volusia"],
    partnerType: "Community Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-42",
    name: "The Bridge (Neighborhood Center of West Volusia)",
    category: "Shelters & Housing",
    address: "421 S Palmetto Ave, DeLand, FL 32720",
    lat: 29.0219345,
    lng: -81.3040635,
    phone: "(386) 734-8120 ext. 601",
    website: "https://neighborhoodcenterwv.org/contact/",
    description: "West Volusia's crisis center and day center: 30 emergency low-barrier crisis beds, a day center with showers, communal dining and commercial kitchen, and case management. Open 24 hours.",
    hoursText: "Open 24 hours",
    schedule: {0: [[0, 24]], 1: [[0, 24]], 2: [[0, 24]], 3: [[0, 24]], 4: [[0, 24]], 5: [[0, 24]], 6: [[0, 24]]},
    tags: ["Shelter", "Showers", "Day Center", "Meals", "Volusia"],
    partnerType: "Community Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-43",
    name: "First Step Shelter",
    category: "Shelters & Housing",
    address: "3889 W International Speedway Blvd, Daytona Beach, FL 32124",
    lat: 29.1688549,
    lng: -81.0861951,
    phone: "(386) 361-3800",
    website: "https://firststepshelter.org/",
    description: "Comprehensive homeless shelter with a pathway-to-housing program, case management, a Safe Zone, an outreach helpline, and help obtaining ID and health insurance. Intake is by referral through the website or outreach helpline — call ahead.",
    hoursText: "Call for intake",
    schedule: {},
    tags: ["Shelter", "Case Management", "Housing Help", "ID Help", "Volusia"],
    partnerType: "Regional Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-44",
    name: "Halifax Urban Ministries — Hope Place",
    category: "Shelters & Housing",
    address: "1340 Wright St, Daytona Beach, FL 32117",
    lat: 29.2415906,
    lng: -81.0706279,
    phone: "(386) 317-5886",
    website: "https://www.halifaxurbanministries.org/",
    description: "Hope Place provides emergency shelter and transitional housing for families with children and youth who have aged out of foster care. Also the Feed-a-Family food pantry and the Bridge of Hope mobile pantry, which serves daily hot lunches.",
    hoursText: "Feed-a-Family pantry Thursdays 2:00 – 3:00 PM; mobile pantry Thursdays 3:00 – 4:00 PM",
    schedule: {4: [[14, 15], [15, 16]]},
    tags: ["Shelter", "Groceries", "Families", "Hot Meals", "Volusia"],
    partnerType: "Regional Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-45",
    name: "Palmetto House (Mid-Florida Housing Partnership)",
    category: "Shelters & Housing",
    address: "336 S Palmetto Ave, Daytona Beach, FL 32114",
    lat: 29.2061683,
    lng: -81.0190682,
    phone: "(386) 253-4895",
    website: "https://www.mfhp.org/palmetto-house",
    description: "The region's largest transitional housing facility with 48 private rooms for single adults experiencing homelessness. Drug-free with screening required; state-issued ID required. Residents may stay up to 24 months. Intake is by appointment, not walk-in.",
    hoursText: "Intakes by appointment only, Tue–Thu 9:00 AM – 1:00 PM",
    schedule: {2: [[9, 13]], 3: [[9, 13]], 4: [[9, 13]]},
    tags: ["Transitional Housing", "Single Adults", "Case Management", "Appointment Required", "Volusia"],
    partnerType: "Housing Provider",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-46",
    name: "Family Renew Community — Daytona Beach",
    category: "Shelters & Housing",
    address: "105 South St, Daytona Beach, FL 32114",
    lat: 29.2000355,
    lng: -81.0147043,
    phone: "(386) 258-5993",
    website: "https://familyrenew.org/daytona-beach-residential-campus",
    description: "Transitional housing for 6–24 months for single mothers experiencing homelessness with their children. 11 apartments with supportive services toward permanent housing.",
    hoursText: "Call for intake",
    schedule: {},
    tags: ["Transitional Housing", "Families", "Women", "Volusia"],
    partnerType: "Housing Provider",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-47",
    name: "Safe Place Transitional Housing",
    category: "Shelters & Housing",
    address: "605 N Segrave St, Daytona Beach, FL 32114",
    lat: 29.2216964,
    lng: -81.0303281,
    phone: "(386) 316-6040",
    website: "https://www.newsmyrnahousing.com/",
    description: "24-bed transitional housing exclusively for people aged 62 and older who are experiencing homelessness, with stays of up to two years.",
    hoursText: "Call for intake",
    schedule: {},
    tags: ["Transitional Housing", "Seniors", "Volusia"],
    partnerType: "Housing Provider",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-48",
    name: "Volusia/Flagler County Coalition for the Homeless",
    category: "Charity Free Services",
    address: "324 North St, Daytona Beach, FL 32114",
    lat: 29.2216834,
    lng: -81.0298553,
    phone: "(386) 279-0029",
    website: "https://www.vfcch.org/",
    description: "Continuum of Care lead agency for Volusia and Flagler counties and the coordinated-entry point into the local homeless response system: assessment and referral to shelter and housing programs.",
    hoursText: "Call for assessment",
    schedule: {},
    tags: ["Coordinated Entry", "Referrals", "Volusia", "Flagler"],
    partnerType: "Continuum of Care",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-49",
    name: "VCAN — Volusia County Assistance Network",
    category: "Charity Free Services",
    address: "207 White St, Daytona Beach, FL 32114",
    lat: 29.2036676,
    lng: -81.046654,
    phone: "(386) 999-1888",
    website: "https://www.fbhcommunity.org/programs/vcan/",
    description: "Food and basic-needs relief for East Volusia County. One-time delivery of food for families with children under 18, seniors, and students under 24.",
    hoursText: "Call or text to arrange",
    schedule: {},
    tags: ["Groceries", "Delivery", "Seniors", "Families", "Volusia"],
    partnerType: "Community Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-50",
    name: "Second Harvest Food Bank — Volusia Branch",
    category: "Food Banks",
    address: "320 North St, Daytona Beach, FL 32114",
    lat: 29.221614,
    lng: -81.0296262,
    phone: "(386) 257-4499",
    website: "https://feedhopenow.org/",
    description: "Regional food-bank warehouse supplying partner agencies across Volusia. This is a distribution center, not a walk-in pantry — food is not handed out to individuals here. Use the Second Harvest Food Finder or call 2-1-1 to locate a partner pantry.",
    hoursText: "Warehouse only — no public distribution",
    schedule: {},
    tags: ["Food Bank Warehouse", "No Walk-In", "Volusia", "Referrals"],
    partnerType: "Regional Food Bank",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-51",
    name: "Florida Department of Health in Volusia County",
    category: "Charity Free Services",
    address: "1845 Holsonback Dr, Daytona Beach, FL 32117",
    lat: 29.2128613,
    lng: -81.078688,
    phone: "(386) 274-0500",
    website: "https://volusia.floridahealth.gov/",
    description: "Public health clinic offering immunizations, family planning, STD and HIV services, and TB testing, plus vital records (birth and death certificates). WIC referrals available.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM; Vital Statistics until 4:45 PM",
    schedule: {1: [[8, 17]], 2: [[8, 17]], 3: [[8, 17]], 4: [[8, 17]], 5: [[8, 17]]},
    tags: ["Healthcare", "Vital Records", "Immunizations", "Volusia"],
    partnerType: "Public Health",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-52",
    name: "Volusia County Human Services — Community Assistance",
    category: "Charity Free Services",
    address: "1845 Holsonback Dr, Daytona Beach, FL 32117",
    lat: 29.2128613,
    lng: -81.078688,
    phone: "(386) 736-5955",
    website: "https://www.volusia.org/services/community-services/community-assistance/",
    description: "County community assistance programs including emergency financial help, utility assistance, and referrals to local agencies.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM",
    schedule: {1: [[8, 17]], 2: [[8, 17]], 3: [[8, 17]], 4: [[8, 17]], 5: [[8, 17]]},
    tags: ["Rent Help", "Utilities", "Referrals", "Volusia"],
    partnerType: "County Program",
    capacityStatus: "High Demand",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-53",
    name: "Avenues 12 Women's Recovery Houses",
    category: "Shelters & Housing",
    address: "204 South St, Daytona Beach, FL 32114",
    lat: 29.2000452,
    lng: -81.016092,
    phone: "(386) 256-4955",
    description: "Transitional sober-living residences for women recovering from alcohol and drug addiction. This is a structured recovery program, NOT an emergency shelter for the general homeless population, and it is not a walk-in service.",
    hoursText: "Call for intake",
    schedule: {},
    tags: ["Recovery", "Women", "Transitional Housing", "Not Emergency", "Volusia"],
    partnerType: "Recovery Program",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-54",
    name: "God's Bathhouse",
    category: "Showers & Hygiene",
    address: "Mobile — Volusia County, New Smyrna Beach, FL",
    lat: 29.0258,
    lng: -80.927,
    phone: "",
    website: "https://godsbathhouse.org/",
    description: "Mobile shower van bringing showers, clean clothes, and personal hygiene supplies to people experiencing homelessness. Rotates between host sites in New Smyrna Beach and DeLand.",
    hoursText: "Mon 11:00 AM – 1:00 PM New Smyrna Beach; Thu 11:00 AM – 1:00 PM New Smyrna Beach; Sat 9:00 – 11:00 AM DeLand (2nd & 4th Sat)",
    schedule: {1: [[11, 13]], 4: [[11, 13]], 6: [[9, 11]]},
    tags: ["Showers", "Hygiene", "Clothing", "Mobile Services", "No ID Required"],
    partnerType: "Mobile Service",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-55",
    name: "Frog Ministry",
    category: "Food Banks",
    address: "1708 S Ridgewood Ave, Edgewater, FL 32132",
    lat: 28.9750064,
    lng: -80.8980271,
    phone: "(386) 957-3822",
    description: "Food pantry and basic-needs assistance in Edgewater. Published hours differ between the ministry's own site and the county health department — call before going.",
    hoursText: "Mon–Wed 9:00 AM – 5:00 PM; Fri–Sat 9:00 AM – 2:00 PM (call to confirm)",
    schedule: {1: [[9, 17]], 2: [[9, 17]], 3: [[9, 17]], 5: [[9, 14]], 6: [[9, 14]]},
    tags: ["Groceries", "Volusia", "Call to Confirm"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-56",
    name: "Our Lady of Lourdes Catholic Church Food Pantry",
    category: "Food Banks",
    address: "201 University Blvd, Daytona Beach, FL 32118",
    lat: 29.2409371,
    lng: -81.0207302,
    phone: "(386) 290-9876",
    description: "Parish food pantry serving the Daytona Beach area.",
    hoursText: "Tuesdays & Thursdays 8:00 – 10:30 AM",
    schedule: {2: [[8, 10.5]], 4: [[8, 10.5]]},
    tags: ["Groceries", "Volusia"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-57",
    name: "Prince of Peace Social Service",
    category: "Food Banks",
    address: "600 S Nova Rd, Ormond Beach, FL 32174",
    lat: 29.2657739,
    lng: -81.0792258,
    phone: "(386) 676-1695",
    description: "Food pantry serving Ormond Beach and the surrounding area.",
    hoursText: "Mon–Fri 9:00 AM – 1:00 PM",
    schedule: {1: [[9, 13]], 2: [[9, 13]], 3: [[9, 13]], 4: [[9, 13]], 5: [[9, 13]]},
    tags: ["Groceries", "Volusia"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Volusia",
    lastVerified: "2026-09-25",
  },
];

const ORANGE_RESOURCES: Resource[] = [
  {
    id: "res-58",
    name: "Christian Service Center for Central Florida",
    category: "Charity Free Services",
    address: "808 W Central Blvd, Orlando, FL 32805",
    lat: 28.541913,
    lng: -81.390374,
    phone: "407-425-2523",
    website: "https://www.christianservicecenter.org/downtownorlando",
    description: "Comprehensive day services: food pantry, clothing, emergency financial assistance, a free daily lunch, thrift store, case management, mail service, and it is one of Orange County's Coordinated Entry Access Points. Walk-ins are first-come, first-served and it often runs at capacity.",
    hoursText: "Family & Emergency Services Mon–Fri 9:00 AM – 4:00 PM; Daily Bread lunch Mon–Fri from 12:00 PM, Sun from 11:00 AM, closed Sat",
    schedule: {0: [[11, 12]], 1: [[9, 16]], 2: [[9, 16]], 3: [[9, 16]], 4: [[9, 16]], 5: [[9, 16]], 6: [[12, 13]]},
    tags: ["Food", "Clothing", "Rent Help", "Mail Service", "Coordinated Entry", "Orange County"],
    partnerType: "Regional Partner",
    capacityStatus: "High Demand",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-59",
    name: "Coalition for the Homeless of Central Florida",
    category: "Shelters & Housing",
    address: "18 N Terry Ave, Orlando, FL 32801",
    lat: 28.5435707,
    lng: -81.3869173,
    phone: "407-652-5300",
    website: "https://www.centralfloridahomeless.org/contact",
    description: "Emergency shelter for single men, women, and families with intake and assessment, plus drop-in showers, laundry, and mail service. A nightly community dinner is open to anyone and needs no ID.",
    hoursText: "Intake Center Mon–Fri 7:00 AM – 3:00 PM; community dinner daily 6:45 PM; showers by group Mon–Thu",
    schedule: {1: [[9, 16]], 2: [[9, 16]], 3: [[9, 16]], 4: [[9, 16]], 5: [[9, 16]]},
    tags: ["Shelter", "Meals", "Showers", "Laundry", "Intake", "Orange County"],
    partnerType: "Regional Partner",
    capacityStatus: "Limited Beds",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-60",
    name: "Second Harvest Food Bank of Central Florida",
    category: "Food Banks",
    address: "411 Mercy Dr, Orlando, FL 32805",
    lat: 28.5491946,
    lng: -81.430269,
    phone: "407-295-1066",
    website: "https://feedhopenow.org/find-help/food-finder/",
    description: "Wholesale food distribution to roughly 870 partner feeding agencies across seven counties, including SNAP application help and referrals. This is a warehouse — food is not distributed directly to individuals here. Use the Food Finder to locate a partner pantry, or call 2-1-1.",
    hoursText: "Warehouse only — no public distribution",
    schedule: {},
    tags: ["Food Bank Warehouse", "No Walk-In", "SNAP Help", "Orange County", "Referrals"],
    partnerType: "Regional Food Bank",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-61",
    name: "Samaritan Resource Center",
    category: "Showers & Hygiene",
    address: "9837 E Colonial Dr, Orlando, FL 32817",
    lat: 28.5534194,
    lng: -81.3222076,
    phone: "407-482-0600",
    website: "https://samaritanresourcecenter.org",
    description: "Drop-in day resource center for adults 18 and over who are experiencing or at risk of homelessness in East Orange County: showers, laundry, mail, meals, clothing, hygiene supplies, case management, mental health counseling, ID and birth-certificate help, benefits application assistance, employment help, haircuts, and medical referrals. No appointment required.",
    hoursText: "Mon–Thu 9:00 AM – 4:30 PM; Fri 9:00 AM – 2:00 PM; closed weekends",
    schedule: {1: [[9, 16.5]], 2: [[9, 16.5]], 3: [[9, 16.5]], 4: [[9, 16.5]], 5: [[9, 14]]},
    tags: ["Showers", "Laundry", "Mail Service", "Meals", "Case Management", "No ID Required", "Orange County"],
    partnerType: "Community Partner",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-62",
    name: "United Against Poverty Orlando",
    category: "Charity Free Services",
    address: "150 W Michigan St, Orlando, FL 32806",
    lat: 28.5129021,
    lng: -81.3725105,
    phone: "407-650-0774",
    website: "https://uporlando.org/crisis-stabilization-program",
    description: "Crisis Stabilization Program with case management, the Member Share Grocery Program for low-cost groceries and fresh produce, SNAP application help, workforce training and placement, and computer access. Also hosts Orange County's Coordinated Entry Hub every Friday afternoon.",
    hoursText: "Life Enrichment Center Mon–Fri 9:00 AM – 4:00 PM; Coordinated Entry Hub Fridays 1:30 – 4:00 PM",
    schedule: {1: [[9, 16]], 2: [[9, 16]], 3: [[9, 16]], 4: [[9, 16]], 5: [[9, 16]]},
    tags: ["Groceries", "SNAP Help", "Case Management", "Job Training", "Computer Access", "Orange County"],
    partnerType: "Community Partner",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-63",
    name: "IDignity",
    category: "Charity Free Services",
    address: "425 N Magnolia Ave, Orlando, FL 32801",
    lat: 28.5484394,
    lng: -81.3766883,
    phone: "407-792-1374",
    website: "https://idignity.org/get-help/",
    description: "Free help obtaining Florida ID cards and driver's licenses, U.S. birth certificates, Social Security cards, and other vital records for U.S. citizens and legal residents. Runs Identification Service Days at Jackie's Place; appointments are strongly encouraged and walk-ins should arrive before 9:00 AM.",
    hoursText: "Identification Service Days: Tuesdays & Thursdays 8:30 AM – 2:00 PM",
    schedule: {2: [[8.5, 14]], 4: [[8.5, 14]]},
    tags: ["ID Help", "Documents", "Immigration-Safe", "Appointment Encouraged", "Orange County"],
    partnerType: "Nonprofit",
    capacityStatus: "Normal Supply",
    triageCategory: "id_tech",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-64",
    name: "Covenant House Florida — Orlando",
    category: "Shelters & Housing",
    address: "711 N Magnolia Ave, Orlando, FL 32803",
    lat: 28.5533373,
    lng: -81.3767746,
    phone: "407-482-0404",
    website: "https://www.covenanthousefl.org/",
    description: "Services for youth aged 18–24 who are experiencing or at risk of homelessness: transitional housing, case management, street outreach, education, and workforce development. Also an Orange County Coordinated Entry Access Point. Confirm by phone whether a bed is available.",
    hoursText: "Mon–Sat approximately 8:00 AM – 6:00 PM — call for current hours",
    schedule: {},
    tags: ["Youth", "Transitional Housing", "Case Management", "Ages 18-24", "Orange County"],
    partnerType: "Regional Partner",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-65",
    name: "Orlando Union Rescue Mission — Family Home",
    category: "Shelters & Housing",
    address: "1525 W Washington St, Orlando, FL 32805",
    lat: 28.543971,
    lng: -81.401703,
    phone: "407-423-2131",
    website: "https://ourm.org/services/",
    description: "Long-term transitional housing for single women, single mothers with children, single fathers with children, and married couples with children. Offers meals, laundry, childcare, counseling, and job-readiness programs. This location does NOT serve single men.",
    hoursText: "Intake by appointment; three meals a day served 365 days a year",
    schedule: {},
    tags: ["Shelter", "Women", "Families", "Children", "Meals", "Orange County"],
    partnerType: "Faith-Based",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-66",
    name: "Orlando Union Rescue Mission — Project Hope",
    category: "Shelters & Housing",
    address: "3300 W Colonial Dr, Orlando, FL 32808",
    lat: 28.5519577,
    lng: -81.4169092,
    phone: "407-423-3596",
    website: "https://ourm.org/services/",
    description: "Emergency shelter and long-term addiction-recovery program for single men, with three meals a day, counseling, skills training, and career guidance. This is the location for single homeless men.",
    hoursText: "Call for intake",
    schedule: {},
    tags: ["Shelter", "Men", "Recovery", "Meals", "Job Training", "Orange County"],
    partnerType: "Faith-Based",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-67",
    name: "SALT Outreach — Downtown Drop-In Center",
    category: "Showers & Hygiene",
    address: "1025 S Orange Blossom Trail, Orlando, FL 32805",
    lat: 28.5295655,
    lng: -81.3970025,
    phone: "866-237-2589",
    description: "Mobile drop-in center: free showers, laundry, storage, restrooms, mail service, charging stations, phone use, hygiene products, clothing, haircuts, case management, and mental health counseling. No ID required and open to anyone experiencing homelessness. Youth aged 16–24 are served at a separate site on W Colonial Dr.",
    hoursText: "Mon–Thu 9:00 AM – 5:00 PM; Fri 9:00 AM – 4:00 PM; closed weekends",
    schedule: {1: [[9, 17]], 2: [[9, 17]], 3: [[9, 17]], 4: [[9, 17]], 5: [[9, 16]]},
    tags: ["Showers", "Laundry", "Mail Service", "Hygiene", "No ID Required", "Orange County"],
    partnerType: "Community Partner",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-68",
    name: "Catholic Charities — Agape Mission Market",
    category: "Food Banks",
    address: "1771 N Semoran Blvd, Orlando, FL 32807",
    lat: 28.513649,
    lng: -81.3109305,
    phone: "407-658-1818",
    website: "https://cflcc.org/mission-markets/",
    description: "Choice food pantry with fresh produce, meat, dairy, and groceries, at the Catholic Charities main office. Food assistance is by appointment only through the online form — this is not a walk-in pantry.",
    hoursText: "By appointment only: Mon, Wed & Fri",
    schedule: {1: [[9, 12.5]], 3: [[9, 12.5]], 5: [[9, 12.5]]},
    tags: ["Groceries", "Fresh Produce", "Appointment Required", "Orange County"],
    partnerType: "Faith Partner",
    capacityStatus: "Normal Supply",
    triageCategory: "food",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-69",
    name: "Orange County Crisis Assistance Program",
    category: "Charity Free Services",
    address: "Orlando, Orlando, FL",
    lat: 28.5383,
    lng: -81.3792,
    phone: "407-836-6500",
    website: "https://www.ocfl.net/CommunityFamilyServices/CitizenResourceOutreach/CrisisAssistanceProgram.aspx",
    description: "One-time emergency financial assistance for rent, mortgage, and utilities (electric, gas, and water only), with budget counseling and referrals. Appointment-based, not a walk-in service — call to be screened.",
    hoursText: "Phone screening Mon–Fri 8:30 AM – 12:00 PM & 1:30 – 4:00 PM",
    schedule: {1: [[8.5, 12], [13.5, 16]], 2: [[8.5, 12], [13.5, 16]], 3: [[8.5, 12], [13.5, 16]], 4: [[8.5, 12], [13.5, 16]], 5: [[8.5, 12], [13.5, 16]]},
    tags: ["Rent Help", "Utilities", "Budget Counseling", "Appointment Required", "Orange County"],
    partnerType: "County Program",
    capacityStatus: "High Demand",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-70",
    name: "Homeless Services Network — Coordinated Entry Hub",
    category: "Charity Free Services",
    address: "150 W Michigan St, Orlando, FL 32806",
    lat: 28.5129021,
    lng: -81.3725105,
    phone: "",
    website: "https://www.hsncfl.org/help",
    description: "The official entry point for homeless housing assistance in Orange County. The Hub at United Against Poverty Orlando runs every Friday afternoon and sees about 12 households, first-come first-served. Assessment does not mean immediate housing — eligibility applies and waiting lists are common. Call 2-1-1 if you cannot attend in person.",
    hoursText: "Fridays 1:30 – 4:00 PM",
    schedule: {5: [[13.5, 16]]},
    tags: ["Coordinated Entry", "Housing Help", "Assessment", "Orange County"],
    partnerType: "Continuum of Care",
    capacityStatus: "Call for availability",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-71",
    name: "2-1-1 Central Florida (Heart of Florida United Way)",
    category: "Charity Free Services",
    address: "Orlando, Orlando, FL",
    lat: 28.5383,
    lng: -81.3792,
    phone: "211",
    website: "https://www.hfuw.org/get-help/211-help/",
    description: "Free, confidential 24/7 helpline for food, housing, utilities, healthcare, employment, and counseling across Orange, Osceola, and Seminole counties. Text your ZIP code to 898-211 or chat online.",
    hoursText: "24/7",
    schedule: {0: [[0, 24]], 1: [[0, 24]], 2: [[0, 24]], 3: [[0, 24]], 4: [[0, 24]], 5: [[0, 24]], 6: [[0, 24]]},
    tags: ["24/7", "Helpline", "Orange County", "Crisis"],
    partnerType: "Helpline",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
  {
    id: "res-72",
    name: "Matthew's Hope Ministries Outreach Center",
    category: "Charity Free Services",
    address: "611 Business Park Blvd, Winter Garden, FL 34787",
    lat: 28.5653,
    lng: -81.5862,
    phone: "407-905-9500",
    website: "https://www.matthewshopeministries.org/",
    description: "Hot breakfast plus lunch to go, showers, shave, haircut, laundry service, a food pantry, and clothing as needed for West Orange County. First-time guests undergo a background check.",
    hoursText: "Tuesdays & Thursdays 7:30 – 11:00 AM",
    schedule: {2: [[7.5, 11]], 4: [[7.5, 11]]},
    tags: ["Hot Meals", "Showers", "Laundry", "Groceries", "West Orange"],
    partnerType: "Faith Partner",
    capacityStatus: "Call for availability",
    triageCategory: "food",
    county: "Orange",
    lastVerified: "2026-09-25",
  },
];

/**
 * Helplines, state agencies, and legal-aid lines that serve all three counties but
 * are not a place to travel to. They carry a nominal coordinate only so the distance
 * sort does not filter them out; `mobileOnly` keeps the UI from offering directions.
 */
const STATEWIDE_RESOURCES: Resource[] = [
  {
    id: "res-73",
    name: "Florida DCF MyACCESS (SNAP / Food Assistance)",
    category: "Charity Free Services",
    address: "Statewide, Statewide, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "1-850-300-4323",
    website: "https://myaccess.myflfamilies.com/",
    description: "Apply online for Florida SNAP food assistance, Temporary Cash Assistance, and Medicaid. The call center is open Mon–Fri 8:00 AM – 5:00 PM. Applying for benefits is free — never pay a fee to a third party.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM",
    schedule: {1: [[8, 17]], 2: [[8, 17]], 3: [[8, 17]], 4: [[8, 17]], 5: [[8, 17]]},
    tags: ["SNAP", "Medicaid", "Cash Assistance", "Statewide", "Benefits"],
    partnerType: "State Agency",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-74",
    name: "Florida KidCare",
    category: "Charity Free Services",
    address: "Statewide, Statewide, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "1-888-540-5437",
    website: "https://floridakidcare.org/",
    description: "Florida's children's health insurance program (CHIP) with year-round enrollment and a free application. Call Mon–Fri 7:30 AM – 7:30 PM for help or a paper application.",
    hoursText: "Mon–Fri 7:30 AM – 7:30 PM",
    schedule: {1: [[7.5, 19.5]], 2: [[7.5, 19.5]], 3: [[7.5, 19.5]], 4: [[7.5, 19.5]], 5: [[7.5, 19.5]]},
    tags: ["Health Insurance", "Children", "Families", "Statewide"],
    partnerType: "State Program",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-75",
    name: "Florida Medicaid Helpline",
    category: "Charity Free Services",
    address: "Statewide, Statewide, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "1-877-254-1055",
    website: "https://ahca.myflorida.com/medicaid/recipient-resources.html",
    description: "Medicaid coverage questions and recipient assistance. Apply for Medicaid eligibility through DCF's MyACCESS portal.",
    hoursText: "Mon–Fri 8:00 AM – 5:00 PM",
    schedule: {1: [[8, 17]], 2: [[8, 17]], 3: [[8, 17]], 4: [[8, 17]], 5: [[8, 17]]},
    tags: ["Medicaid", "Healthcare", "Statewide"],
    partnerType: "State Agency",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-76",
    name: "Florida WIC Program",
    category: "Food Banks",
    address: "Statewide, Statewide, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "1-800-342-3556",
    website: "https://www.floridahealth.gov/individual-family-health/womens-health/wic/",
    description: "Nutrition benefits, breastfeeding support, and nutrition education for pregnant and breastfeeding women, infants, and children under 5 who meet income guidelines. Appointments are scheduled through local county health departments.",
    hoursText: "Call to schedule a certification appointment",
    schedule: {},
    tags: ["WIC", "Nutrition", "Families", "Statewide"],
    partnerType: "State Program",
    capacityStatus: "Open & Ready",
    triageCategory: "food",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-77",
    name: "988 Suicide & Crisis Lifeline",
    category: "Charity Free Services",
    address: "National, National, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "988",
    website: "https://988lifeline.org/",
    description: "Free and confidential crisis support for mental health, suicide, and substance use, 24/7. Call or text 988, or chat online. Spanish text and chat available. Veterans can call 988 and press 1, or text 838255.",
    hoursText: "24/7",
    schedule: {0: [[0, 24]], 1: [[0, 24]], 2: [[0, 24]], 3: [[0, 24]], 4: [[0, 24]], 5: [[0, 24]], 6: [[0, 24]]},
    tags: ["Crisis", "Mental Health", "24/7", "Suicide Prevention", "Statewide"],
    partnerType: "Crisis Line",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-78",
    name: "Florida Abuse Hotline",
    category: "Charity Free Services",
    address: "Statewide, Statewide, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "1-800-962-2873",
    website: "https://www.myflfamilies.com/services/abuse/abuse-hotline",
    description: "Report known or suspected child abuse, neglect, or abandonment, and abuse, neglect, or exploitation of vulnerable adults. Accepts reports 24/7 and also takes human-trafficking reports.",
    hoursText: "24/7",
    schedule: {0: [[0, 24]], 1: [[0, 24]], 2: [[0, 24]], 3: [[0, 24]], 4: [[0, 24]], 5: [[0, 24]], 6: [[0, 24]]},
    tags: ["Crisis", "Abuse Reporting", "24/7", "Statewide"],
    partnerType: "State Agency",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-79",
    name: "VA National Call Center for Homeless Veterans",
    category: "Shelters & Housing",
    address: "National, National, FL",
    lat: 28.7617,
    lng: -80.8625,
    phone: "1-877-424-3838",
    website: "https://department.va.gov/homeless/nationalcallcenter/",
    description: "Free and confidential 24/7 help line for veterans who are homeless or at risk of homelessness, and for their families and providers. Counselors connect callers to VA homeless programs including HUD-VASH, SSVF, and GPD.",
    hoursText: "24/7",
    schedule: {0: [[0, 24]], 1: [[0, 24]], 2: [[0, 24]], 3: [[0, 24]], 4: [[0, 24]], 5: [[0, 24]], 6: [[0, 24]]},
    tags: ["Veterans", "Housing Help", "24/7", "Statewide"],
    partnerType: "Federal Program",
    capacityStatus: "Open & Ready",
    triageCategory: "shelter",
    county: "Statewide",
    lastVerified: "2026-09-25",
    mobileOnly: true,
  },
  {
    id: "res-80",
    name: "Community Legal Services of Mid-Florida",
    category: "Charity Free Services",
    address: "122 E Colonial Dr, Suite 200, Orlando, FL 32801",
    lat: 28.5383,
    lng: -81.3792,
    phone: "1-800-405-1417",
    website: "https://www.legalaccessforall.org/gethelp/",
    description: "No-cost civil legal aid for Central Florida: eviction and tenant defense, foreclosure, benefits denials, family law and domestic-violence injunctions, and consumer law. Offices are open by appointment only; apply through the helpline first. Brevard County is served by Brevard County Legal Aid instead.",
    hoursText: "Helpline Mon, Wed, Thu 8:30 AM – 4:30 PM; Tue until 5:30 PM; Fri until 3:30 PM",
    schedule: {1: [[8.5, 16.5]], 2: [[8.5, 17.5]], 3: [[8.5, 16.5]], 4: [[8.5, 16.5]], 5: [[8.5, 15.5]]},
    tags: ["Legal Aid", "Eviction", "Benefits", "Statewide", "Appointment Required"],
    partnerType: "Legal Aid",
    capacityStatus: "Open & Ready",
    triageCategory: "id_tech",
    county: "Statewide",
    lastVerified: "2026-09-25",
  },
];

export const ALL_RESOURCES: Resource[] = [
  ...BREVARD_RESOURCES,
  ...VOLUSIA_RESOURCES,
  ...ORANGE_RESOURCES,
  ...STATEWIDE_RESOURCES,
];

export type AvailabilityStatus = "OPEN" | "SOON" | "CLOSED" | "UNKNOWN";

export type Availability = {
  status: AvailabilityStatus;
  label: string;
};

const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function formatTime(decimalTime: number): string {
  const hrs = Math.floor(decimalTime);
  const mins = Math.round((decimalTime - hrs) * 60);
  const period = hrs >= 12 ? "PM" : "AM";
  const displayHrs = hrs % 12 === 0 ? 12 : hrs % 12;
  const displayMins = mins < 10 ? `0${mins}` : String(mins);
  return `${displayHrs}:${displayMins} ${period}`;
}

/**
 * Availability is derived only from hours the organization publishes.
 *
 * Entries whose hours are unconfirmed carry an empty `schedule`, so they fall through
 * to "Call for schedule" rather than showing an "Open now" badge that may be wrong.
 */
export function getNextAvailableInfo(resource: Resource, now = new Date()): Availability {
  const currentDay = now.getDay();
  const currentHour = now.getHours() + now.getMinutes() / 60;
  const today = resource.schedule[currentDay] ?? [];

  for (const [open, close] of today) {
    if (currentHour >= open && currentHour < close) {
      const remaining = Math.ceil(close - currentHour);
      return { status: "OPEN", label: `Open now · closes in ~${remaining}h` };
    }
  }

  const laterToday = today.find(([open]) => currentHour < open);
  if (laterToday) {
    return { status: "SOON", label: `Opens today at ${formatTime(laterToday[0])}` };
  }

  for (let offset = 1; offset <= 7; offset += 1) {
    const ranges = resource.schedule[(currentDay + offset) % 7];
    if (ranges?.length) {
      const dayLabel = offset === 1 ? "Tomorrow" : DAY_NAMES[(currentDay + offset) % 7];
      return { status: "CLOSED", label: `Next: ${dayLabel} at ${formatTime(ranges[0][0])}` };
    }
  }

  return { status: "UNKNOWN", label: "Call for schedule" };
}

export function calculateDistanceMiles(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number,
): number {
  const R = 3958.8;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

export type ProcessedResource = Resource & {
  distanceMiles: number;
  nextAvail: Availability;
};

export function processResources(
  origin: Coordinates,
  maxDistance: number,
  options: {
    category: string;
    tag: string;
    query: string;
    onlySaved: boolean;
    savedIds: string[];
    openNow?: boolean;
  },
): ProcessedResource[] {
  const q = options.query.trim().toLowerCase();
  return ALL_RESOURCES.map((res) => ({
    ...res,
    distanceMiles: calculateDistanceMiles(origin.lat, origin.lng, res.lat, res.lng),
    nextAvail: getNextAvailableInfo(res),
  }))
    // Phone-based and mobile entries have no meaningful distance, so the radius
    // filter must not drop them.
    .filter((res) => res.mobileOnly || res.distanceMiles <= maxDistance)
    .filter((res) => {
      if (options.onlySaved && !options.savedIds.includes(res.id)) return false;
      if (options.openNow && res.nextAvail.status !== "OPEN") return false;
      if (options.category !== "All" && res.category !== options.category) return false;
      if (options.tag !== "All" && !res.tags.includes(options.tag)) return false;
      if (!q) return true;
      return (
        res.name.toLowerCase().includes(q) ||
        res.description.toLowerCase().includes(q) ||
        res.address.toLowerCase().includes(q) ||
        res.tags.some((t) => t.toLowerCase().includes(q))
      );
    })
    .sort((a, b) => {
      const rank = { OPEN: 0, SOON: 1, CLOSED: 2, UNKNOWN: 3 };
      const statusDelta = rank[a.nextAvail.status] - rank[b.nextAvail.status];
      if (statusDelta !== 0) return statusDelta;
      return a.distanceMiles - b.distanceMiles;
    });
}

export function resourcesForTriage(need: TriageNeed): Resource[] {
  return ALL_RESOURCES.filter(
    (res) =>
      res.triageCategory === need ||
      res.tags.some((t) => t.toLowerCase().includes(need.replace("_", " "))),
  );
}

export function telHref(phone: string): string {
  // A naive strip of every non-digit turns "(386) 734-8120 ext. 601" into the
  // 13-digit "3867348120601", which no phone can dial - the extension is not part of
  // the number. RFC 3966 carries it in the `;ext=` parameter instead. Phones ignore
  // that parameter rather than misdialing, so the entry stays usable either way.
  const ext = phone.match(/\b(?:ext\.?|extension|x)\s*(\d{1,6})\b/i);
  const base = (ext ? phone.slice(0, ext.index) : phone).replace(/[^\d+]/g, "");
  if (!base) return "";
  return ext ? `tel:${base};ext=${ext[1]}` : `tel:${base}`;
}

/**
 * A directions link that hands off to whatever map app the phone already has.
 *
 * The Google Maps URL scheme is the only one that works on both iOS and Android: it
 * opens the installed Google Maps app when there is one and falls back to the web
 * page when there is not. Apple Maps would only work on iOS, and the `geo:` scheme
 * only on Android, so neither can be the single link for everyone.
 *
 * No travel mode is passed. The map app already has walking, driving, and transit
 * built in and remembers what the person chose last time, so duplicating that choice
 * on our page would add buttons without adding any capability.
 */
export function directionsHref(address: string): string {
  return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address)}`;
}
